name: build-check

on: [push]

jobs:
  ubuntu:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Adopted from: https://github.com/sourcegraph/sourcegraph/blob/main/cmd/gitserver/p4-fusion-install-alpine.sh#L82
    - name: Install OpenSSL 1.0.2t
      run: |
        mkdir openssl-src
        wget https://www.openssl.org/source/openssl-1.0.2t.tar.gz
        tar -C openssl-src -xzf openssl-1.0.2t.tar.gz --strip 1
        pushd openssl-src
        ./config
        make build_libs
        sudo make install
        popd
    
    - name: Install Helix Core C++ API
      run: |
        mkdir -p p4-fusion-src/vendor/helix-core-api/linux
        wget https://www.perforce.com/downloads/perforce/r21.1/bin.linux26x86_64/p4api.tgz
        tar -C p4-fusion-src/vendor/helix-core-api/linux -xzf p4api.tgz --strip 1

    - name: Configure CMake cache
      run: |
        ./generate_cache.sh Release

    - name: Build p4-fusion
      run: |
        ./build.sh

    - name: Test p4-fusion
      run: |
        ldd build/p4-fusion/p4-fusion
        ./build/p4-fusion/p4-fusion
