name: format-check

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: 'p4-fusion tests'
        extensions: 'h,cc'
        clangFormatVersion: 12.0.1
